pipeline {
    agent any

    options {
        // Keep only the last 10 builds to save disk space
        buildDiscarder(logRotator(numToKeepStr: '10'))
        // Timeout the entire pipeline after 60 minutes
        timeout(time: 60, unit: 'MINUTES')
    }

    environment {
        // Path to pytest in virtual environment
        PYTEST_PATH = "${WORKSPACE}\\.venv\\Scripts\\pytest.exe"
        PROJECT_ROOT = "${WORKSPACE}"
    }

    stages {
        stage('Setup') {
            steps {
                script {
                    echo "Step 1: Cleaning old data..."
                    // Remove old allure results and reports using PowerShell (supports wildcards)
                    powershell "Remove-Item -Recurse -Force allure-results* -ErrorAction SilentlyContinue"
                    powershell "Remove-Item -Recurse -Force report -ErrorAction SilentlyContinue"
                    echo "Cleaning complete."
                }
            }
        }

        stage('Run Parallel Tests') {
            parallel {
                stage('Chrome Tests') {
                    steps {
                        script {
                            echo "Running Chrome tests..."
                            bat "\"%PYTEST_PATH%\" --executor=grid --browser=chrome --alluredir=allure-results-chrome -v"
                        }
                    }
                }

                stage('Firefox Tests') {
                    steps {
                        script {
                            echo "Running Firefox tests..."
                            bat "\"%PYTEST_PATH%\" --executor=grid --browser=firefox --alluredir=allure-results-firefox -v"
                        }
                    }
                }

                stage('Edge Tests') {
                    steps {
                        script {
                            echo "Running Edge tests..."
                            bat "\"%PYTEST_PATH%\" --executor=grid --browser=edge --alluredir=allure-results-edge -v"
                        }
                    }
                }
            }
        }

        stage('Verify Results') {
            steps {
                script {
                    echo "Step 3: Verifying test results..."

                    def chromeExists = fileExists 'allure-results-chrome'
                    def firefoxExists = fileExists 'allure-results-firefox'
                    def edgeExists = fileExists 'allure-results-edge'

                    echo "Chrome results: ${chromeExists ? 'Found' : 'Missing'}"
                    echo "Firefox results: ${firefoxExists ? 'Found' : 'Missing'}"
                    echo "Edge results: ${edgeExists ? 'Found' : 'Missing'}"

                    if (!chromeExists || !firefoxExists || !edgeExists) {
                        echo "WARNING: Some browser results are missing!"
                    }
                }
            }
        }

        stage('Generate Report') {
            steps {
                script {
                    echo "Step 4: Allure results collected. Report will be generated by Allure plugin..."
                    // The Allure plugin will automatically generate and publish the report
                    echo "Report will be available in Jenkins UI after build completes."
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                script {
                    echo "Step 5: Archiving test results for debugging..."
                    // Archive individual browser results for debugging
                    archiveArtifacts artifacts: 'allure-results-*/**/*', allowEmptyArchive: true
                }
            }
        }
    }

    post {
        always {
            script {
                echo "Pipeline execution completed."
            }
            allure includeProperties: false, jdk: '', properties: [], reportBuildPolicy: 'ALWAYS', results: [[path: 'allure-results-*']]
        }
        success {
            echo "All tests completed successfully!"
        }
        failure {
            echo "Pipeline failed. Check the logs for details."
        }
    }
}